apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilitysoft
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mobilitysoft
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # allows 3 pods max across both deployments (2 steady + 1 surge)
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mobilitysoft
    spec:
      containers:
        - name: mobilitysoft
          image: docker.io/funnyadd/mobilitysoft-eq10:DEBUG
          ports:
            - name: http
              containerPort: 5002
          envFrom:
            - secretRef:
                name: mobilitysoft-app-secrets
          resources:
            requests:
              cpu: "90m"
              memory: "128Mi"
            limits:
              cpu: "180m"
              memory: "256Mi"
