apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilitysoft
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mobilitysoft
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mobilitysoft
    spec:
      containers:
        - name: mobilitysoft
          image: docker.io/funnyadd/mobilitysoft-eq10:DEBUG
          ports:
            - name: http
              containerPort: 5002
          envFrom:
            - secretRef:
                name: mobilitysoft-app-secrets
