apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistent-volume-claim
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: grafana-manual
  resources:
    requests:
      storage: 5Gi
