apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # allows 3 pods max across both deployments (2 steady + 1 surge)
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metrics
    spec:
      containers:
        - name: metrics
          image: docker.io/funnyadd/metrics-a25-grp1-eq10:DEBUG
          ports:
            - name: http
              containerPort: 5001
          envFrom:
            - secretRef:
                name: metrics-app-secrets
          resources:
            requests:
              cpu: "90m"
              memory: "128Mi"
            limits:
              cpu: "180m"
              memory: "256Mi"
