apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: staging-log680.home.adammihajlovic.ca
      http:
        paths:
          - path: /team10/metrics(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: metrics
                port:
                  number: 5001
