apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics
spec:
  ingressClassName: nginx
  rules:
    - host: staging-metrics-api.home.adammihajlovic.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metrics
                port:
                  number: 5001
