apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobilitysoft-backend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: log680.home.adammihajlovic.ca
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mobilitysoft
                port:
                  number: 5002
