apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - app-secrets.yaml
  - frontend-ingress.yaml
  - backend-ingress.yaml
patches:
  - path: patch-deployment.yaml
