apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilitysoft
spec:
  template:
    spec:
      containers:
        - name: mobilitysoft
          image: docker.io/funnyadd/mobilitysoft-eq10:prod-20251103-220930-91dc7e3 # {"$imagepolicy": "flux-system:mobilitysoft-prod"}
