apiVersion: apps/v1
kind: Deployment
metadata:
  name: log680
spec:
  template:
    spec:
      containers:
        - name: metrics
          image: docker.io/funnyadd/metrics-a25-grp1-eq10:staging-20251102-192055-ec99da9 # {"$imagepolicy": "flux-system:metrics-staging"}
        - name: mobilitysoft
          image: docker.io/funnyadd/mobilitysoft-eq10:staging-20251102-152635-cd4caf2 # {"$imagepolicy": "flux-system:mobilitysoft-staging"}
