apiVersion: apps/v1
kind: Deployment
metadata:
  name: log680
spec:
  template:
    spec:
      containers:
        - name: metrics
          image: docker.io/funnyadd/metrics-a25-grp1-eq10:prod-20251006-213905-bbce225 # {"$imagepolicy": "flux-system:metrics-prod"}
        - name: mobilitysoft
          image: docker.io/funnyadd/mobilitysoft-eq10:prod-20251103-220802-91dc7e3 # {"$imagepolicy": "flux-system:mobilitysoft-prod"}
