apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - namespaces-kustomization.yaml
  - prod-kustomization.yaml
  - staging-kustomization.yaml
  - image/automation.yaml

  # Metrics API LOG680
  - image/metrics-policies.yaml
  - image/metrics-repository.yaml

  # Mobilitysoft LOG680
  - image/mobilitysoft-policies.yaml
  - image/mobilitysoft-repository.yaml
