apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - namespaces-kustomization.yaml
  - prod-kustomization.yaml
  - staging-kustomization.yaml
  - image/automation-prod.yaml
  - image/automation-staging.yaml
