apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/home/environments/prod
  targetNamespace: prod
  dependsOn:
    - name: namespaces
  decryption:
    provider: sops
    secretRef:
      name: sops-age
