apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobilitysoft
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: staging-log680.home.adammihajlovic.ca
      http:
        paths:
          - path: /team10/mobilitysoft(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mobilitysoft
                port:
                  number: 5002
