apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - app-secrets.yaml
  - ingress.yaml
  - image-policy.yaml
  - image-repository.yaml
patches:
  - path: patch-deployment.yaml
