apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilitysoft
spec:
  template:
    spec:
      containers:
        - name: mobilitysoft
          image: docker.io/funnyadd/mobilitysoft-eq10:staging-20251210-100807-27e3496 # {"$imagepolicy": "flux-system:mobilitysoft-staging"}
