apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/metrics/overlays/staging
  - ../../../../apps/mobilitysoft/overlays/staging
  - ../../../../apps/grafana/overlays/staging
